### ISSUE TITLE
1.20.4 Fabric

### ISSUE THREAD

**Issue by Crystal-Spider** [PieKing1215/DripSounds#18]
Will there be a 1.20.4 Fabric version?

**Comment by ghost** [comment]
the 1.19.4-1.20 version loads fine in 1.20.4 and works so I don't see the problem however I do notice that the drip sounds sound too quiet.

**Comment by Crystal-Spider** [comment]
Would be nice to have it marked for 1.20.4 too to add it to modpacks easily

**Comment by PieKing1215** [comment]
Sure, sounds like it works so I'll mark it compatible. If any issues come up lmk
As for the quietness, the volume is controlled both by the volume slider in the config and by the sound category's volume
(eg. the category defaults to Ambient so the volume is also multiplied by your ambient sounds volume. You can change the category in the config)
