### ISSUE TITLE
NOISSUE Consider not including ClothConfig.

### ISSUE THREAD

**Issue by K0-RR** [PieKing1215/DripSounds#3]
The file size would go down from 941 KiB >> 94.3 KiB. Many mods require ClothConfig and many of them bundle it so it gets included 50 times in any basic modpack. Even the modpack size gets like 30 MB bigger.

**Comment by PieKing1215** [comment]
Thanks for letting me know!
I just added a "no-bundled-cloth" jar as an additional file on the latest release on [github](https://github.com/PieKing1215/DripSounds-Fabric/releases/tag/v0.2.2-1.17), [curseforge](https://www.curseforge.com/minecraft/mc-mods/dripsounds-fabric/files/3393101), and [modrinth](https://modrinth.com/mod/dripsounds-fabric/version/w7UflcNW). (I'll probably stop making bundled versions in the future)
I'm not sure how the curseforge desktop app handles "additional files" when making modpacks so let me know if that doesn't work!

**Comment by itsdinkd** [comment]
The config file is empty that generates.. is this normal? (for the regular mod with config API included)

**Comment by PieKing1215** [comment]
It might not populate the file until you edit and save the config once in-game? I'm not exactly sure how that works.

**Comment by itsdinkd** [comment]
there is nothing to edit in modmenu, it doesn't give an option to edit
anything. and then the file in config folder is blank

**Comment by PieKing1215** [comment]
Starting in [v0.3.0](https://github.com/PieKing1215/DripSounds-Fabric/releases/tag/v0.3.0) cloth config is no longer bundled at all.
I've also been doing this in my other mods as they get updated.

@red2blue If you're still having that problem you can make a new issue as it's not really related to this one.
