### ISSUE TITLE
Mod incompatible with Sodium

### ISSUE THREAD

**Issue by YeahImRose** [PieKing1215/DripSounds#4]
Sodium, `fabric-sodium`, should be added as an incompatibility to `fabric.mod.json` or the issue should be resolved.

**Comment by cjtganzon** [comment]
it is working now with the current iris and sodium mods

**Comment by PieKing1215** [comment]
Sodium and Iris compatibility should be working since version 0.2.2
I just tested with the latest 1.17.1 release of Sodium and Iris and they both seem to work fine.
If @YeahImRose has any details whatsoever about problems they can reopen this issue
